--- # This is a structural yaml example to install httpd

- hosts: webservers
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes

  vars:
    username: myuser
    somevar: testvar

  tasks:
  - name: Un-Install APACHE-2 server on Ubuntu Nodes
    apt:
      name: apache2
      state: absent
    notify:
    - confirm_apache_service

  handlers:
  - name: confirm_apache_service
    service:
      name: apache2
      state: stopped


